# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ui_test_manager/ui_test_manager/ui_test_manager.h
SOURCES += ./ui_test_manager/ui_test_manager/main.cpp \
    ./ui_test_manager/ui_test_manager/ui_test_manager.cpp
FORMS += ./ui_test_manager/ui_test_manager/ui_test_manager.ui
RESOURCES += ui_test_manager.qrc
